// <auto-generated />
using System;
using BahceFiyatTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BahceFiyatTakip.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260622152638_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BahceFiyatTakip.Models.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SearchUrlTemplate")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Markets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://www.migros.com.tr",
                            IsActive = true,
                            Name = "Migros",
                            SearchUrlTemplate = "https://www.migros.com.tr/arama?q={0}"
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://www.a101.com.tr",
                            IsActive = true,
                            Name = "A101",
                            SearchUrlTemplate = "https://www.a101.com.tr/arama/?search_text={0}"
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://www.carrefoursa.com",
                            IsActive = true,
                            Name = "CarrefourSA",
                            SearchUrlTemplate = "https://www.carrefoursa.com/search/?text={0}"
                        },
                        new
                        {
                            Id = 4,
                            BaseUrl = "https://www.sokmarket.com.tr",
                            IsActive = true,
                            Name = "Sok",
                            SearchUrlTemplate = "https://www.sokmarket.com.tr/arama?q={0}"
                        },
                        new
                        {
                            Id = 5,
                            BaseUrl = "https://www.bim.com.tr",
                            IsActive = true,
                            Name = "BIM",
                            SearchUrlTemplate = "https://www.bim.com.tr"
                        });
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.PriceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLive")
                        .HasColumnType("bit");

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("ProductId", "MarketId", "CheckedAt");

                    b.ToTable("PriceRecords");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.PriceRecord", b =>
                {
                    b.HasOne("BahceFiyatTakip.Models.Market", "Market")
                        .WithMany("PriceRecords")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BahceFiyatTakip.Models.Product", "Product")
                        .WithMany("PriceRecords")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.Market", b =>
                {
                    b.Navigation("PriceRecords");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.Product", b =>
                {
                    b.Navigation("PriceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
