// <auto-generated />
using System;
using BahceFiyatTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BahceFiyatTakip.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260623195240_AddNewProductsAndFixNames")]
    partial class AddNewProductsAndFixNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BahceFiyatTakip.Models.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SearchUrlTemplate")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Markets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://www.migros.com.tr",
                            IsActive = true,
                            Name = "Migros",
                            SearchUrlTemplate = "https://www.migros.com.tr/rest/products/search?q={0}&sayfa=0&sira=ONERILENLER&webSubdomain=www"
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://www.a101.com.tr",
                            IsActive = true,
                            Name = "A101",
                            SearchUrlTemplate = "https://www.a101.com.tr/arama/?search_text={0}"
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://www.carrefoursa.com",
                            IsActive = true,
                            Name = "CarrefourSA",
                            SearchUrlTemplate = "https://www.carrefoursa.com/search/?text={0}"
                        },
                        new
                        {
                            Id = 4,
                            BaseUrl = "https://www.sokmarket.com.tr",
                            IsActive = true,
                            Name = "Sok",
                            SearchUrlTemplate = "https://www.sokmarket.com.tr/arama?q={0}"
                        },
                        new
                        {
                            Id = 5,
                            BaseUrl = "https://www.bim.com.tr",
                            IsActive = false,
                            Name = "BIM"
                        },
                        new
                        {
                            Id = 6,
                            BaseUrl = "https://search.brave.com",
                            IsActive = false,
                            Name = "Web Arama"
                        });
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.PriceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsLive")
                        .HasColumnType("bit");

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<string>("MatchedTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVarietyId")
                        .HasColumnType("int");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("ProductVarietyId");

                    b.HasIndex("ProductId", "MarketId", "CheckedAt");

                    b.ToTable("PriceRecords");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Mandalina",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Limon",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Lime",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Finger Lime",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Portakal",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Tropikal",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Avokado",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Diğer Ürünler",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Meyve",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Nar",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Tropikal",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Ejder Meyvesi",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Tropikal",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Çarkıfelek",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Tropikal",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Mango",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Sebze",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Domates",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Diğer",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Limon Otu",
                            Unit = "Demet"
                        });
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.ProductSearchAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProductVarietyId")
                        .HasColumnType("int");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVarietyId", "Query")
                        .IsUnique();

                    b.ToTable("ProductSearchAliases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Priority = 1,
                            ProductVarietyId = 1,
                            Query = "okitsu mandalina"
                        },
                        new
                        {
                            Id = 2,
                            Priority = 2,
                            ProductVarietyId = 1,
                            Query = "okitsu mandalina kg"
                        },
                        new
                        {
                            Id = 3,
                            Priority = 3,
                            ProductVarietyId = 1,
                            Query = "okitsu fiyat"
                        },
                        new
                        {
                            Id = 4,
                            Priority = 1,
                            ProductVarietyId = 2,
                            Query = "satsuma mandalina"
                        },
                        new
                        {
                            Id = 5,
                            Priority = 2,
                            ProductVarietyId = 2,
                            Query = "satsuma mandalina kg"
                        },
                        new
                        {
                            Id = 6,
                            Priority = 3,
                            ProductVarietyId = 2,
                            Query = "satsuma fiyat"
                        },
                        new
                        {
                            Id = 7,
                            Priority = 1,
                            ProductVarietyId = 3,
                            Query = "klemantin mandalina"
                        },
                        new
                        {
                            Id = 8,
                            Priority = 2,
                            ProductVarietyId = 3,
                            Query = "clementine mandalina"
                        },
                        new
                        {
                            Id = 9,
                            Priority = 3,
                            ProductVarietyId = 3,
                            Query = "klemantin fiyat"
                        },
                        new
                        {
                            Id = 10,
                            Priority = 1,
                            ProductVarietyId = 4,
                            Query = "orri mandalina"
                        },
                        new
                        {
                            Id = 11,
                            Priority = 2,
                            ProductVarietyId = 4,
                            Query = "orri mandarin"
                        },
                        new
                        {
                            Id = 12,
                            Priority = 3,
                            ProductVarietyId = 4,
                            Query = "orri fiyat"
                        },
                        new
                        {
                            Id = 13,
                            Priority = 1,
                            ProductVarietyId = 5,
                            Query = "murcott mandalina"
                        },
                        new
                        {
                            Id = 14,
                            Priority = 2,
                            ProductVarietyId = 5,
                            Query = "murcott mandarin"
                        },
                        new
                        {
                            Id = 15,
                            Priority = 3,
                            ProductVarietyId = 5,
                            Query = "murcott fiyat"
                        },
                        new
                        {
                            Id = 16,
                            Priority = 1,
                            ProductVarietyId = 6,
                            Query = "mayer limon"
                        },
                        new
                        {
                            Id = 17,
                            Priority = 2,
                            ProductVarietyId = 6,
                            Query = "meyer limon"
                        },
                        new
                        {
                            Id = 18,
                            Priority = 3,
                            ProductVarietyId = 6,
                            Query = "mayer limon kg"
                        },
                        new
                        {
                            Id = 19,
                            Priority = 1,
                            ProductVarietyId = 7,
                            Query = "kirmizi limon"
                        },
                        new
                        {
                            Id = 20,
                            Priority = 2,
                            ProductVarietyId = 7,
                            Query = "red lemon"
                        },
                        new
                        {
                            Id = 21,
                            Priority = 3,
                            ProductVarietyId = 7,
                            Query = "kirmizi limon kg"
                        },
                        new
                        {
                            Id = 22,
                            Priority = 1,
                            ProductVarietyId = 8,
                            Query = "enterdonat limon"
                        },
                        new
                        {
                            Id = 23,
                            Priority = 2,
                            ProductVarietyId = 8,
                            Query = "enterdonat limon kg"
                        },
                        new
                        {
                            Id = 24,
                            Priority = 3,
                            ProductVarietyId = 8,
                            Query = "interdonato limon"
                        },
                        new
                        {
                            Id = 25,
                            Priority = 1,
                            ProductVarietyId = 9,
                            Query = "lamas limon"
                        },
                        new
                        {
                            Id = 26,
                            Priority = 2,
                            ProductVarietyId = 9,
                            Query = "klasik limon kg"
                        },
                        new
                        {
                            Id = 27,
                            Priority = 3,
                            ProductVarietyId = 9,
                            Query = "lamas limon kg"
                        },
                        new
                        {
                            Id = 28,
                            Priority = 1,
                            ProductVarietyId = 10,
                            Query = "kokulu limon"
                        },
                        new
                        {
                            Id = 29,
                            Priority = 2,
                            ProductVarietyId = 10,
                            Query = "kokulu limon kg"
                        },
                        new
                        {
                            Id = 30,
                            Priority = 3,
                            ProductVarietyId = 10,
                            Query = "limonata limonu"
                        },
                        new
                        {
                            Id = 31,
                            Priority = 1,
                            ProductVarietyId = 11,
                            Query = "grande limon"
                        },
                        new
                        {
                            Id = 32,
                            Priority = 2,
                            ProductVarietyId = 11,
                            Query = "italyan limon"
                        },
                        new
                        {
                            Id = 33,
                            Priority = 3,
                            ProductVarietyId = 11,
                            Query = "grande limon kg"
                        },
                        new
                        {
                            Id = 34,
                            Priority = 1,
                            ProductVarietyId = 12,
                            Query = "tatli limon"
                        },
                        new
                        {
                            Id = 35,
                            Priority = 2,
                            ProductVarietyId = 12,
                            Query = "sweet lemon kg"
                        },
                        new
                        {
                            Id = 36,
                            Priority = 3,
                            ProductVarietyId = 12,
                            Query = "tatli limon kg"
                        },
                        new
                        {
                            Id = 37,
                            Priority = 1,
                            ProductVarietyId = 13,
                            Query = "lime kg"
                        },
                        new
                        {
                            Id = 38,
                            Priority = 2,
                            ProductVarietyId = 13,
                            Query = "yesil limon lime"
                        },
                        new
                        {
                            Id = 39,
                            Priority = 3,
                            ProductVarietyId = 13,
                            Query = "lime fiyat"
                        },
                        new
                        {
                            Id = 40,
                            Priority = 1,
                            ProductVarietyId = 14,
                            Query = "kaffir lime"
                        },
                        new
                        {
                            Id = 41,
                            Priority = 2,
                            ProductVarietyId = 14,
                            Query = "kafir lime"
                        },
                        new
                        {
                            Id = 42,
                            Priority = 3,
                            ProductVarietyId = 14,
                            Query = "kaffir limon kg"
                        },
                        new
                        {
                            Id = 43,
                            Priority = 1,
                            ProductVarietyId = 15,
                            Query = "tatli lime"
                        },
                        new
                        {
                            Id = 44,
                            Priority = 2,
                            ProductVarietyId = 15,
                            Query = "sweet lime kg"
                        },
                        new
                        {
                            Id = 45,
                            Priority = 3,
                            ProductVarietyId = 15,
                            Query = "tatli lime fiyat"
                        },
                        new
                        {
                            Id = 46,
                            Priority = 1,
                            ProductVarietyId = 16,
                            Query = "kan lime"
                        },
                        new
                        {
                            Id = 47,
                            Priority = 2,
                            ProductVarietyId = 16,
                            Query = "blood lime"
                        },
                        new
                        {
                            Id = 48,
                            Priority = 3,
                            ProductVarietyId = 16,
                            Query = "kirmizi lime"
                        },
                        new
                        {
                            Id = 49,
                            Priority = 1,
                            ProductVarietyId = 17,
                            Query = "verde finger lime"
                        },
                        new
                        {
                            Id = 50,
                            Priority = 2,
                            ProductVarietyId = 17,
                            Query = "finger lime verde"
                        },
                        new
                        {
                            Id = 51,
                            Priority = 3,
                            ProductVarietyId = 17,
                            Query = "havyar limon verde"
                        },
                        new
                        {
                            Id = 52,
                            Priority = 1,
                            ProductVarietyId = 18,
                            Query = "rose finger lime"
                        },
                        new
                        {
                            Id = 53,
                            Priority = 2,
                            ProductVarietyId = 18,
                            Query = "finger lime rose"
                        },
                        new
                        {
                            Id = 54,
                            Priority = 3,
                            ProductVarietyId = 18,
                            Query = "pembe havyar limon"
                        },
                        new
                        {
                            Id = 55,
                            Priority = 1,
                            ProductVarietyId = 19,
                            Query = "sunpearl finger lime"
                        },
                        new
                        {
                            Id = 56,
                            Priority = 2,
                            ProductVarietyId = 19,
                            Query = "finger lime sunpearl"
                        },
                        new
                        {
                            Id = 57,
                            Priority = 1,
                            ProductVarietyId = 20,
                            Query = "blossom finger lime"
                        },
                        new
                        {
                            Id = 58,
                            Priority = 2,
                            ProductVarietyId = 20,
                            Query = "finger lime blossom"
                        },
                        new
                        {
                            Id = 59,
                            Priority = 1,
                            ProductVarietyId = 21,
                            Query = "washington portakal"
                        },
                        new
                        {
                            Id = 60,
                            Priority = 2,
                            ProductVarietyId = 21,
                            Query = "finike portakal"
                        },
                        new
                        {
                            Id = 61,
                            Priority = 3,
                            ProductVarietyId = 21,
                            Query = "washington portakal kg"
                        },
                        new
                        {
                            Id = 62,
                            Priority = 1,
                            ProductVarietyId = 22,
                            Query = "valensiya portakal"
                        },
                        new
                        {
                            Id = 63,
                            Priority = 2,
                            ProductVarietyId = 22,
                            Query = "valencia portakal kg"
                        },
                        new
                        {
                            Id = 64,
                            Priority = 3,
                            ProductVarietyId = 22,
                            Query = "sikmalik portakal"
                        },
                        new
                        {
                            Id = 65,
                            Priority = 1,
                            ProductVarietyId = 23,
                            Query = "mysticrimson portakal"
                        },
                        new
                        {
                            Id = 66,
                            Priority = 2,
                            ProductVarietyId = 23,
                            Query = "kirmizi etli portakal"
                        },
                        new
                        {
                            Id = 67,
                            Priority = 1,
                            ProductVarietyId = 24,
                            Query = "blushsweet portakal"
                        },
                        new
                        {
                            Id = 68,
                            Priority = 2,
                            ProductVarietyId = 24,
                            Query = "kan portakali"
                        },
                        new
                        {
                            Id = 69,
                            Priority = 1,
                            ProductVarietyId = 25,
                            Query = "seker portakali"
                        },
                        new
                        {
                            Id = 70,
                            Priority = 2,
                            ProductVarietyId = 25,
                            Query = "tatli portakal kg"
                        },
                        new
                        {
                            Id = 71,
                            Priority = 1,
                            ProductVarietyId = 26,
                            Query = "hass avokado"
                        },
                        new
                        {
                            Id = 72,
                            Priority = 2,
                            ProductVarietyId = 26,
                            Query = "puturlu avokado"
                        },
                        new
                        {
                            Id = 73,
                            Priority = 3,
                            ProductVarietyId = 26,
                            Query = "hass avokado kg"
                        },
                        new
                        {
                            Id = 74,
                            Priority = 1,
                            ProductVarietyId = 27,
                            Query = "ettinger avokado"
                        },
                        new
                        {
                            Id = 75,
                            Priority = 2,
                            ProductVarietyId = 27,
                            Query = "ettinger avocado kg"
                        },
                        new
                        {
                            Id = 76,
                            Priority = 1,
                            ProductVarietyId = 28,
                            Query = "bacon avokado"
                        },
                        new
                        {
                            Id = 77,
                            Priority = 2,
                            ProductVarietyId = 28,
                            Query = "bacon avocado kg"
                        },
                        new
                        {
                            Id = 78,
                            Priority = 1,
                            ProductVarietyId = 29,
                            Query = "fuerte avokado"
                        },
                        new
                        {
                            Id = 79,
                            Priority = 2,
                            ProductVarietyId = 29,
                            Query = "fuerte avocado kg"
                        },
                        new
                        {
                            Id = 80,
                            Priority = 1,
                            ProductVarietyId = 30,
                            Query = "cliffton avokado"
                        },
                        new
                        {
                            Id = 81,
                            Priority = 2,
                            ProductVarietyId = 30,
                            Query = "clifton avokado kg"
                        },
                        new
                        {
                            Id = 82,
                            Priority = 1,
                            ProductVarietyId = 31,
                            Query = "bergamot"
                        },
                        new
                        {
                            Id = 83,
                            Priority = 2,
                            ProductVarietyId = 31,
                            Query = "bergamot kg"
                        },
                        new
                        {
                            Id = 84,
                            Priority = 3,
                            ProductVarietyId = 31,
                            Query = "bergamot fiyat"
                        },
                        new
                        {
                            Id = 85,
                            Priority = 1,
                            ProductVarietyId = 32,
                            Query = "kumkuat"
                        },
                        new
                        {
                            Id = 86,
                            Priority = 2,
                            ProductVarietyId = 32,
                            Query = "kamkat"
                        },
                        new
                        {
                            Id = 87,
                            Priority = 3,
                            ProductVarietyId = 32,
                            Query = "kumkuat kg"
                        },
                        new
                        {
                            Id = 88,
                            Priority = 1,
                            ProductVarietyId = 33,
                            Query = "sadok"
                        },
                        new
                        {
                            Id = 89,
                            Priority = 2,
                            ProductVarietyId = 33,
                            Query = "pomelo"
                        },
                        new
                        {
                            Id = 90,
                            Priority = 3,
                            ProductVarietyId = 33,
                            Query = "sadok fiyat"
                        },
                        new
                        {
                            Id = 91,
                            Priority = 1,
                            ProductVarietyId = 34,
                            Query = "beyaz greyfurt"
                        },
                        new
                        {
                            Id = 92,
                            Priority = 2,
                            ProductVarietyId = 34,
                            Query = "white grapefruit kg"
                        },
                        new
                        {
                            Id = 93,
                            Priority = 1,
                            ProductVarietyId = 35,
                            Query = "kirmizi greyfurt"
                        },
                        new
                        {
                            Id = 94,
                            Priority = 2,
                            ProductVarietyId = 35,
                            Query = "red grapefruit kg"
                        },
                        new
                        {
                            Id = 95,
                            Priority = 1,
                            ProductVarietyId = 36,
                            Query = "limekuat"
                        },
                        new
                        {
                            Id = 96,
                            Priority = 2,
                            ProductVarietyId = 36,
                            Query = "limequat"
                        },
                        new
                        {
                            Id = 97,
                            Priority = 3,
                            ProductVarietyId = 36,
                            Query = "limekuat kg"
                        },
                        new
                        {
                            Id = 98,
                            Priority = 1,
                            ProductVarietyId = 37,
                            Query = "turunc"
                        },
                        new
                        {
                            Id = 99,
                            Priority = 2,
                            ProductVarietyId = 37,
                            Query = "acı portakal"
                        },
                        new
                        {
                            Id = 100,
                            Priority = 3,
                            ProductVarietyId = 37,
                            Query = "turunc kg"
                        },
                        new
                        {
                            Id = 101,
                            Priority = 1,
                            ProductVarietyId = 38,
                            Query = "hicaz nar"
                        },
                        new
                        {
                            Id = 102,
                            Priority = 2,
                            ProductVarietyId = 38,
                            Query = "hicaz nar kg"
                        },
                        new
                        {
                            Id = 103,
                            Priority = 3,
                            ProductVarietyId = 38,
                            Query = "nar kg hicaz"
                        },
                        new
                        {
                            Id = 104,
                            Priority = 1,
                            ProductVarietyId = 39,
                            Query = "hicaz 9 eylul nar"
                        },
                        new
                        {
                            Id = 105,
                            Priority = 2,
                            ProductVarietyId = 39,
                            Query = "erkenci nar"
                        },
                        new
                        {
                            Id = 106,
                            Priority = 1,
                            ProductVarietyId = 40,
                            Query = "kirmizi ejder meyvesi"
                        },
                        new
                        {
                            Id = 107,
                            Priority = 2,
                            ProductVarietyId = 40,
                            Query = "dragon fruit kirmizi"
                        },
                        new
                        {
                            Id = 108,
                            Priority = 3,
                            ProductVarietyId = 40,
                            Query = "ejder meyvesi kg"
                        },
                        new
                        {
                            Id = 109,
                            Priority = 1,
                            ProductVarietyId = 41,
                            Query = "sari ejder meyvesi"
                        },
                        new
                        {
                            Id = 110,
                            Priority = 2,
                            ProductVarietyId = 41,
                            Query = "sari dragon fruit"
                        },
                        new
                        {
                            Id = 111,
                            Priority = 1,
                            ProductVarietyId = 42,
                            Query = "mor carkifelek"
                        },
                        new
                        {
                            Id = 112,
                            Priority = 2,
                            ProductVarietyId = 42,
                            Query = "passion fruit mor"
                        },
                        new
                        {
                            Id = 113,
                            Priority = 3,
                            ProductVarietyId = 42,
                            Query = "carkifelek kg"
                        },
                        new
                        {
                            Id = 114,
                            Priority = 1,
                            ProductVarietyId = 43,
                            Query = "sari carkifelek"
                        },
                        new
                        {
                            Id = 115,
                            Priority = 2,
                            ProductVarietyId = 43,
                            Query = "yellow passion fruit"
                        },
                        new
                        {
                            Id = 116,
                            Priority = 1,
                            ProductVarietyId = 44,
                            Query = "kent mango"
                        },
                        new
                        {
                            Id = 117,
                            Priority = 2,
                            ProductVarietyId = 44,
                            Query = "mango kg kent"
                        },
                        new
                        {
                            Id = 118,
                            Priority = 3,
                            ProductVarietyId = 44,
                            Query = "turkiye mango"
                        },
                        new
                        {
                            Id = 119,
                            Priority = 1,
                            ProductVarietyId = 45,
                            Query = "tommy atkins mango"
                        },
                        new
                        {
                            Id = 120,
                            Priority = 2,
                            ProductVarietyId = 45,
                            Query = "tommy mango kg"
                        },
                        new
                        {
                            Id = 121,
                            Priority = 1,
                            ProductVarietyId = 46,
                            Query = "keitt mango"
                        },
                        new
                        {
                            Id = 122,
                            Priority = 2,
                            ProductVarietyId = 46,
                            Query = "yesil mango kg"
                        },
                        new
                        {
                            Id = 123,
                            Priority = 1,
                            ProductVarietyId = 47,
                            Query = "salkimli domates"
                        },
                        new
                        {
                            Id = 124,
                            Priority = 2,
                            ProductVarietyId = 47,
                            Query = "domates salkim kg"
                        },
                        new
                        {
                            Id = 125,
                            Priority = 1,
                            ProductVarietyId = 48,
                            Query = "san marzano domates"
                        },
                        new
                        {
                            Id = 126,
                            Priority = 2,
                            ProductVarietyId = 48,
                            Query = "san marzano kg"
                        },
                        new
                        {
                            Id = 127,
                            Priority = 1,
                            ProductVarietyId = 49,
                            Query = "cherry domates"
                        },
                        new
                        {
                            Id = 128,
                            Priority = 2,
                            ProductVarietyId = 49,
                            Query = "kiraz domates kg"
                        },
                        new
                        {
                            Id = 129,
                            Priority = 1,
                            ProductVarietyId = 50,
                            Query = "limon otu"
                        },
                        new
                        {
                            Id = 130,
                            Priority = 2,
                            ProductVarietyId = 50,
                            Query = "lemon grass taze"
                        },
                        new
                        {
                            Id = 131,
                            Priority = 3,
                            ProductVarietyId = 50,
                            Query = "limon otu demet"
                        },
                        new
                        {
                            Id = 132,
                            Priority = 1,
                            ProductVarietyId = 51,
                            Query = "kurutulmus limon otu"
                        },
                        new
                        {
                            Id = 133,
                            Priority = 2,
                            ProductVarietyId = 51,
                            Query = "lemon grass kurutulmus"
                        });
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.ProductVariety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HarvestPeriod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique();

                    b.ToTable("ProductVarieties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HarvestPeriod = "Eylül sonu",
                            IsActive = true,
                            Name = "OKİTSU",
                            Notes = "Çekirdeksiz; ilk dönem ekşimsi, sonra tatlılaşır; ilk hasatta yeşil.",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            HarvestPeriod = "Ekim sonu - Kasım",
                            IsActive = true,
                            Name = "SATSUMA",
                            Notes = "Çekirdeksiz; sulu ve tatlı.",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            HarvestPeriod = "Kasım sonu",
                            IsActive = true,
                            Name = "KLEMANTİN",
                            Notes = "Çekirdekli; yoğun aromalı; kısa hasat dönemi.",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            HarvestPeriod = "Ocak sonu",
                            IsActive = true,
                            Name = "ORRİ",
                            Notes = "Çok tatlı; sulu ve aromatik; az çekirdek görülebilir.",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            HarvestPeriod = "Ocak sonu",
                            IsActive = true,
                            Name = "MURCOTT",
                            Notes = "Çekirdekli; yoğun tatlı, hafif ekşi; sert ve parlak kabuklu.",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 6,
                            HarvestPeriod = "Eylül başı",
                            IsActive = true,
                            Name = "MAYER",
                            Notes = "Mandalina-limon aroması; az asitli, bol sulu.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "KIRMIZI LİMON",
                            Notes = "Portakal ve limon karışımı aroma; çekirdekli; hafif ekşi.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            HarvestPeriod = "Eylül sonu",
                            IsActive = true,
                            Name = "ENTERDONAT",
                            Notes = "En ekşi limon; kalın kabuklu.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 9,
                            HarvestPeriod = "Aralık - Nisan",
                            IsActive = true,
                            Name = "LAMAS",
                            Notes = "Klasik limon; tam limon aroması; çay için ideal.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 10,
                            HarvestPeriod = "Mart başı",
                            IsActive = true,
                            Name = "KOKULU LİMON",
                            Notes = "Limonata için ideal; çok sulu.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "GRANDE",
                            Notes = "İtalyan kökenli; kalın kabuklu; reçel ve içeceklerde kullanılır.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "TATLI LİMON",
                            Notes = "Ekşilik yoktur; limonata için uygundur.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "LIME",
                            Notes = "İnce kabuklu; sulu; aroması yüksek.",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "KAFFIR LIME",
                            Notes = "Çok yoğun aroma; az sulu; yemek ve soslarda kullanılır.",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "TATLI LIME",
                            Notes = "Mandalinaya benzer; ekşi değil, tatlıdır.",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "KAN LIME",
                            Notes = "Kırmızı tonlu; nadir çeşit.",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "VERDE",
                            Notes = "Finger lime; keskin aroma; asidi yüksek; parlak yeşil taneler.",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "ROSE",
                            Notes = "Finger lime; pembe taneli; asidi dengeli; daha sulu.",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "SUNPEARL",
                            Notes = "Finger lime; sarı-yeşil; mat ve sert taneli.",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "BLOSSOM",
                            Notes = "Finger lime; uzun ve iri taneli.",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 21,
                            HarvestPeriod = "Kasım başı",
                            IsActive = true,
                            Name = "WASHINGTON",
                            Notes = "Finike portakalı; çok tatlı; çekirdeksiz.",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 22,
                            HarvestPeriod = "Nisan - Eylül",
                            IsActive = true,
                            Name = "VALENSİYA",
                            Notes = "Çekirdekli; sıkmalık ve yemelik.",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Name = "MYSTICRIMSON",
                            Notes = "Kırmızı etli; hafif ekşimsi; ince kabuklu.",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Name = "BLUSHSWEET",
                            Notes = "Kan portakalı; pembe iç renk; tatlı; ince kabuklu.",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Name = "ŞEKER PORTAKALI",
                            Notes = "Çok tatlı; asidi düşük.",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            Name = "HASS",
                            Notes = "Pütürlü avokado; en yüksek yağ oranı; güçlü aroma.",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            Name = "ETTINGER",
                            Notes = "Armut şekilli; parlak kabuklu.",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            Name = "BACON",
                            Notes = "İnce kabuklu; hafif lezzetli.",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 29,
                            IsActive = true,
                            Name = "FUERTE",
                            Notes = "Hafif pütürlü; ince kabuklu.",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 30,
                            IsActive = true,
                            Name = "CLIFFTON",
                            Notes = "Yağ oranı düşük; sulu yapı.",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 31,
                            IsActive = true,
                            Name = "BERGAMOT",
                            Notes = "Meyvesi yenmez; kabuğu reçel ve çayda kullanılır.",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 32,
                            IsActive = true,
                            Name = "KUMKUAT",
                            Notes = "Kabuğuyla yenir; dışı tatlı, içi ekşi.",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 33,
                            IsActive = true,
                            Name = "ŞADOK",
                            Notes = "Pomelo + greyfurt aroması; kalın kabuklu.",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 34,
                            IsActive = true,
                            Name = "BEYAZ GREYFURT",
                            Notes = "Beyaz iç ve dış renk.",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 35,
                            IsActive = true,
                            Name = "KIRMIZI GREYFURT",
                            Notes = "Kırmızı iç renk; daha yumuşak tat.",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 36,
                            IsActive = true,
                            Name = "LİMEKUAT",
                            Notes = "Kumkuat-lime melezi; ekşi-tatlı denge.",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 37,
                            IsActive = true,
                            Name = "TURUNÇ",
                            Notes = "Acı portakal; reçel, likör ve parfümde kullanılır.",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 38,
                            HarvestPeriod = "Eylül - Kasım",
                            IsActive = true,
                            Name = "HİCAZ",
                            Notes = "En yaygın Türk nar çeşidi; koyu kırmızı taneli; tatlı-ekşi.",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 39,
                            HarvestPeriod = "Eylül",
                            IsActive = true,
                            Name = "HICAZ 9 EYLÜL",
                            Notes = "Erkenci Hicaz; ince kabuklu.",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 40,
                            IsActive = true,
                            Name = "KIRMIZI EJDER",
                            Notes = "Kırmızı kabuklu; beyaz etli; hafif tatlı.",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 41,
                            IsActive = true,
                            Name = "SARIMIN EJDER",
                            Notes = "Sarı kabuklu; beyaz etli; en tatlı çeşit.",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 42,
                            IsActive = true,
                            Name = "MOR ÇARKIFELEK",
                            Notes = "Mor kabuklu; küçük; yoğun aroma.",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 43,
                            IsActive = true,
                            Name = "SARI ÇARKIFELEK",
                            Notes = "Sarı kabuklu; büyük; daha az yoğun.",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 44,
                            HarvestPeriod = "Temmuz - Eylül",
                            IsActive = true,
                            Name = "KENT",
                            Notes = "En yaygın Türkiye mangoso; tatlı ve lifli.",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 45,
                            IsActive = true,
                            Name = "TOMMY ATKINS",
                            Notes = "Kırmızı-yeşil; lifli; uzun raf ömrü.",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 46,
                            IsActive = true,
                            Name = "KEITT",
                            Notes = "Yeşil kabuk; sarı et; az lifli; tatlı.",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 47,
                            IsActive = true,
                            Name = "SALKIMLI",
                            Notes = "Salkım domates; orta boy; dengeli tat.",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 48,
                            IsActive = true,
                            Name = "SAN MARZANO",
                            Notes = "İtalyan çeşidi; salça ve soslar için ideal.",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 49,
                            IsActive = true,
                            Name = "CHERRY DOMATES",
                            Notes = "Kiraz domates; tatlı ve sulu.",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 50,
                            IsActive = true,
                            Name = "TAZE LİMON OTU",
                            Notes = "Taze demet; yemek ve çay için.",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 51,
                            IsActive = true,
                            Name = "KURUTULMUŞ",
                            Notes = "Kurutulmuş limon otu; çay için.",
                            ProductId = 13
                        });
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.PriceRecord", b =>
                {
                    b.HasOne("BahceFiyatTakip.Models.Market", "Market")
                        .WithMany("PriceRecords")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BahceFiyatTakip.Models.Product", "Product")
                        .WithMany("PriceRecords")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BahceFiyatTakip.Models.ProductVariety", "ProductVariety")
                        .WithMany("PriceRecords")
                        .HasForeignKey("ProductVarietyId");

                    b.Navigation("Market");

                    b.Navigation("Product");

                    b.Navigation("ProductVariety");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.ProductSearchAlias", b =>
                {
                    b.HasOne("BahceFiyatTakip.Models.ProductVariety", "ProductVariety")
                        .WithMany("SearchAliases")
                        .HasForeignKey("ProductVarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariety");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.ProductVariety", b =>
                {
                    b.HasOne("BahceFiyatTakip.Models.Product", "Product")
                        .WithMany("Varieties")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.Market", b =>
                {
                    b.Navigation("PriceRecords");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.Product", b =>
                {
                    b.Navigation("PriceRecords");

                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.ProductVariety", b =>
                {
                    b.Navigation("PriceRecords");

                    b.Navigation("SearchAliases");
                });
#pragma warning restore 612, 618
        }
    }
}
