// <auto-generated />
using System;
using BahceFiyatTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BahceFiyatTakip.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BahceFiyatTakip.Models.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SearchUrlTemplate")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Markets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://www.migros.com.tr",
                            IsActive = true,
                            Name = "Migros",
                            SearchUrlTemplate = "https://www.migros.com.tr/arama?q={0}"
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://www.a101.com.tr",
                            IsActive = true,
                            Name = "A101",
                            SearchUrlTemplate = "https://www.a101.com.tr/arama/?search_text={0}"
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://www.carrefoursa.com",
                            IsActive = true,
                            Name = "CarrefourSA",
                            SearchUrlTemplate = "https://www.carrefoursa.com/search/?text={0}"
                        },
                        new
                        {
                            Id = 4,
                            BaseUrl = "https://www.sokmarket.com.tr",
                            IsActive = true,
                            Name = "Sok",
                            SearchUrlTemplate = "https://www.sokmarket.com.tr/arama?q={0}"
                        },
                        new
                        {
                            Id = 5,
                            BaseUrl = "https://www.bim.com.tr",
                            IsActive = true,
                            Name = "BIM",
                            SearchUrlTemplate = "https://www.bim.com.tr"
                        },
                        new
                        {
                            Id = 6,
                            BaseUrl = "https://search.brave.com",
                            IsActive = true,
                            Name = "Web Arama"
                        });
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.PriceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsLive")
                        .HasColumnType("bit");

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<string>("MatchedTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVarietyId")
                        .HasColumnType("int");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("ProductVarietyId");

                    b.HasIndex("ProductId", "MarketId", "CheckedAt");

                    b.ToTable("PriceRecords");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Mandalina",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Limon",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Lime",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Finger Lime",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Portakal",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Tropikal",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Avokado",
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Narenciye",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Diger Urunler",
                            Unit = "Kg"
                        });
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.ProductSearchAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProductVarietyId")
                        .HasColumnType("int");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVarietyId", "Query")
                        .IsUnique();

                    b.ToTable("ProductSearchAliases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Priority = 1,
                            ProductVarietyId = 1,
                            Query = "okitsu mandalina"
                        },
                        new
                        {
                            Id = 2,
                            Priority = 2,
                            ProductVarietyId = 1,
                            Query = "okitsu mandalina kg"
                        },
                        new
                        {
                            Id = 3,
                            Priority = 3,
                            ProductVarietyId = 1,
                            Query = "okitsu fiyat"
                        },
                        new
                        {
                            Id = 4,
                            Priority = 4,
                            ProductVarietyId = 1,
                            Query = "okitsu fidan meyve"
                        },
                        new
                        {
                            Id = 5,
                            Priority = 1,
                            ProductVarietyId = 2,
                            Query = "satsuma mandalina"
                        },
                        new
                        {
                            Id = 6,
                            Priority = 2,
                            ProductVarietyId = 2,
                            Query = "satsuma mandalina kg"
                        },
                        new
                        {
                            Id = 7,
                            Priority = 3,
                            ProductVarietyId = 2,
                            Query = "satsuma fiyat"
                        },
                        new
                        {
                            Id = 9,
                            Priority = 1,
                            ProductVarietyId = 3,
                            Query = "klemantin mandalina"
                        },
                        new
                        {
                            Id = 10,
                            Priority = 2,
                            ProductVarietyId = 3,
                            Query = "clementine mandalina"
                        },
                        new
                        {
                            Id = 11,
                            Priority = 3,
                            ProductVarietyId = 3,
                            Query = "klemantin fiyat"
                        },
                        new
                        {
                            Id = 13,
                            Priority = 1,
                            ProductVarietyId = 4,
                            Query = "orri mandalina"
                        },
                        new
                        {
                            Id = 14,
                            Priority = 2,
                            ProductVarietyId = 4,
                            Query = "orri mandarin"
                        },
                        new
                        {
                            Id = 15,
                            Priority = 3,
                            ProductVarietyId = 4,
                            Query = "orri fiyat"
                        },
                        new
                        {
                            Id = 17,
                            Priority = 1,
                            ProductVarietyId = 5,
                            Query = "murcott mandalina"
                        },
                        new
                        {
                            Id = 18,
                            Priority = 2,
                            ProductVarietyId = 5,
                            Query = "murcott mandarin"
                        },
                        new
                        {
                            Id = 19,
                            Priority = 3,
                            ProductVarietyId = 5,
                            Query = "murcott fiyat"
                        },
                        new
                        {
                            Id = 21,
                            Priority = 1,
                            ProductVarietyId = 6,
                            Query = "mayer limon"
                        },
                        new
                        {
                            Id = 22,
                            Priority = 2,
                            ProductVarietyId = 6,
                            Query = "meyer limon"
                        },
                        new
                        {
                            Id = 23,
                            Priority = 3,
                            ProductVarietyId = 6,
                            Query = "mayer limon kg"
                        },
                        new
                        {
                            Id = 25,
                            Priority = 1,
                            ProductVarietyId = 7,
                            Query = "kirmizi limon"
                        },
                        new
                        {
                            Id = 26,
                            Priority = 2,
                            ProductVarietyId = 7,
                            Query = "red lemon"
                        },
                        new
                        {
                            Id = 27,
                            Priority = 3,
                            ProductVarietyId = 7,
                            Query = "kirmizi limon fiyat"
                        },
                        new
                        {
                            Id = 29,
                            Priority = 1,
                            ProductVarietyId = 8,
                            Query = "enterdonat limon"
                        },
                        new
                        {
                            Id = 30,
                            Priority = 2,
                            ProductVarietyId = 8,
                            Query = "enterdonat limon kg"
                        },
                        new
                        {
                            Id = 31,
                            Priority = 3,
                            ProductVarietyId = 8,
                            Query = "enternonat limon"
                        },
                        new
                        {
                            Id = 33,
                            Priority = 1,
                            ProductVarietyId = 9,
                            Query = "lamas limon"
                        },
                        new
                        {
                            Id = 34,
                            Priority = 2,
                            ProductVarietyId = 9,
                            Query = "klasik limon"
                        },
                        new
                        {
                            Id = 35,
                            Priority = 3,
                            ProductVarietyId = 9,
                            Query = "lamas limon kg"
                        },
                        new
                        {
                            Id = 37,
                            Priority = 1,
                            ProductVarietyId = 10,
                            Query = "kokulu limon"
                        },
                        new
                        {
                            Id = 38,
                            Priority = 2,
                            ProductVarietyId = 10,
                            Query = "kokulu limon kg"
                        },
                        new
                        {
                            Id = 39,
                            Priority = 3,
                            ProductVarietyId = 10,
                            Query = "limonata limonu"
                        },
                        new
                        {
                            Id = 41,
                            Priority = 1,
                            ProductVarietyId = 11,
                            Query = "grande limon"
                        },
                        new
                        {
                            Id = 42,
                            Priority = 2,
                            ProductVarietyId = 11,
                            Query = "italyan limon"
                        },
                        new
                        {
                            Id = 43,
                            Priority = 3,
                            ProductVarietyId = 11,
                            Query = "grande limon fiyat"
                        },
                        new
                        {
                            Id = 45,
                            Priority = 1,
                            ProductVarietyId = 12,
                            Query = "tatli limon"
                        },
                        new
                        {
                            Id = 46,
                            Priority = 2,
                            ProductVarietyId = 12,
                            Query = "sweet lemon"
                        },
                        new
                        {
                            Id = 47,
                            Priority = 3,
                            ProductVarietyId = 12,
                            Query = "tatli limon fiyat"
                        },
                        new
                        {
                            Id = 49,
                            Priority = 1,
                            ProductVarietyId = 13,
                            Query = "lime"
                        },
                        new
                        {
                            Id = 50,
                            Priority = 2,
                            ProductVarietyId = 13,
                            Query = "lime kg"
                        },
                        new
                        {
                            Id = 51,
                            Priority = 3,
                            ProductVarietyId = 13,
                            Query = "yesil limon"
                        },
                        new
                        {
                            Id = 53,
                            Priority = 1,
                            ProductVarietyId = 14,
                            Query = "kaffir lime"
                        },
                        new
                        {
                            Id = 54,
                            Priority = 2,
                            ProductVarietyId = 14,
                            Query = "kaffir lime fiyat"
                        },
                        new
                        {
                            Id = 55,
                            Priority = 3,
                            ProductVarietyId = 14,
                            Query = "kaffir limon"
                        },
                        new
                        {
                            Id = 57,
                            Priority = 1,
                            ProductVarietyId = 15,
                            Query = "tatli lime"
                        },
                        new
                        {
                            Id = 58,
                            Priority = 2,
                            ProductVarietyId = 15,
                            Query = "sweet lime"
                        },
                        new
                        {
                            Id = 59,
                            Priority = 3,
                            ProductVarietyId = 15,
                            Query = "tatli lime fiyat"
                        },
                        new
                        {
                            Id = 61,
                            Priority = 1,
                            ProductVarietyId = 16,
                            Query = "kan lime"
                        },
                        new
                        {
                            Id = 62,
                            Priority = 2,
                            ProductVarietyId = 16,
                            Query = "blood lime"
                        },
                        new
                        {
                            Id = 63,
                            Priority = 3,
                            ProductVarietyId = 16,
                            Query = "kan lime fiyat"
                        },
                        new
                        {
                            Id = 65,
                            Priority = 1,
                            ProductVarietyId = 17,
                            Query = "verde finger lime"
                        },
                        new
                        {
                            Id = 66,
                            Priority = 2,
                            ProductVarietyId = 17,
                            Query = "finger lime verde"
                        },
                        new
                        {
                            Id = 67,
                            Priority = 3,
                            ProductVarietyId = 17,
                            Query = "havyar limon verde"
                        },
                        new
                        {
                            Id = 69,
                            Priority = 1,
                            ProductVarietyId = 18,
                            Query = "rose finger lime"
                        },
                        new
                        {
                            Id = 70,
                            Priority = 2,
                            ProductVarietyId = 18,
                            Query = "finger lime rose"
                        },
                        new
                        {
                            Id = 71,
                            Priority = 3,
                            ProductVarietyId = 18,
                            Query = "pembe havyar limon"
                        },
                        new
                        {
                            Id = 73,
                            Priority = 1,
                            ProductVarietyId = 19,
                            Query = "sunpearl finger lime"
                        },
                        new
                        {
                            Id = 74,
                            Priority = 2,
                            ProductVarietyId = 19,
                            Query = "finger lime sunpearl"
                        },
                        new
                        {
                            Id = 75,
                            Priority = 3,
                            ProductVarietyId = 19,
                            Query = "sunpearl havyar limon"
                        },
                        new
                        {
                            Id = 77,
                            Priority = 1,
                            ProductVarietyId = 20,
                            Query = "blossom finger lime"
                        },
                        new
                        {
                            Id = 78,
                            Priority = 2,
                            ProductVarietyId = 20,
                            Query = "finger lime blossom"
                        },
                        new
                        {
                            Id = 79,
                            Priority = 3,
                            ProductVarietyId = 20,
                            Query = "blossom havyar limon"
                        },
                        new
                        {
                            Id = 81,
                            Priority = 1,
                            ProductVarietyId = 21,
                            Query = "washington portakal"
                        },
                        new
                        {
                            Id = 82,
                            Priority = 2,
                            ProductVarietyId = 21,
                            Query = "finike portakal"
                        },
                        new
                        {
                            Id = 83,
                            Priority = 3,
                            ProductVarietyId = 21,
                            Query = "washington portakal kg"
                        },
                        new
                        {
                            Id = 85,
                            Priority = 1,
                            ProductVarietyId = 22,
                            Query = "valensiya portakal"
                        },
                        new
                        {
                            Id = 86,
                            Priority = 2,
                            ProductVarietyId = 22,
                            Query = "valencia portakal"
                        },
                        new
                        {
                            Id = 87,
                            Priority = 3,
                            ProductVarietyId = 22,
                            Query = "valensiya portakal kg"
                        },
                        new
                        {
                            Id = 89,
                            Priority = 1,
                            ProductVarietyId = 23,
                            Query = "mysticrimson portakal"
                        },
                        new
                        {
                            Id = 90,
                            Priority = 2,
                            ProductVarietyId = 23,
                            Query = "mystic crimson orange"
                        },
                        new
                        {
                            Id = 91,
                            Priority = 3,
                            ProductVarietyId = 23,
                            Query = "kirmizi etli portakal"
                        },
                        new
                        {
                            Id = 93,
                            Priority = 1,
                            ProductVarietyId = 24,
                            Query = "blushsweet portakal"
                        },
                        new
                        {
                            Id = 94,
                            Priority = 2,
                            ProductVarietyId = 24,
                            Query = "kan portakali blushsweet"
                        },
                        new
                        {
                            Id = 95,
                            Priority = 3,
                            ProductVarietyId = 24,
                            Query = "pembe portakal"
                        },
                        new
                        {
                            Id = 97,
                            Priority = 1,
                            ProductVarietyId = 25,
                            Query = "seker portakali"
                        },
                        new
                        {
                            Id = 98,
                            Priority = 2,
                            ProductVarietyId = 25,
                            Query = "tatli portakal"
                        },
                        new
                        {
                            Id = 99,
                            Priority = 3,
                            ProductVarietyId = 25,
                            Query = "seker portakal kg"
                        },
                        new
                        {
                            Id = 101,
                            Priority = 1,
                            ProductVarietyId = 26,
                            Query = "hass avokado"
                        },
                        new
                        {
                            Id = 102,
                            Priority = 2,
                            ProductVarietyId = 26,
                            Query = "puturlu avokado"
                        },
                        new
                        {
                            Id = 103,
                            Priority = 3,
                            ProductVarietyId = 26,
                            Query = "hass avokado kg"
                        },
                        new
                        {
                            Id = 105,
                            Priority = 1,
                            ProductVarietyId = 27,
                            Query = "ettinger avokado"
                        },
                        new
                        {
                            Id = 106,
                            Priority = 2,
                            ProductVarietyId = 27,
                            Query = "ettinger avocado"
                        },
                        new
                        {
                            Id = 107,
                            Priority = 3,
                            ProductVarietyId = 27,
                            Query = "ettinger avokado kg"
                        },
                        new
                        {
                            Id = 109,
                            Priority = 1,
                            ProductVarietyId = 28,
                            Query = "bacon avokado"
                        },
                        new
                        {
                            Id = 110,
                            Priority = 2,
                            ProductVarietyId = 28,
                            Query = "bacon avocado"
                        },
                        new
                        {
                            Id = 111,
                            Priority = 3,
                            ProductVarietyId = 28,
                            Query = "bacon avokado kg"
                        },
                        new
                        {
                            Id = 113,
                            Priority = 1,
                            ProductVarietyId = 29,
                            Query = "fuerte avokado"
                        },
                        new
                        {
                            Id = 114,
                            Priority = 2,
                            ProductVarietyId = 29,
                            Query = "fuerte avocado"
                        },
                        new
                        {
                            Id = 115,
                            Priority = 3,
                            ProductVarietyId = 29,
                            Query = "fuerte avokado kg"
                        },
                        new
                        {
                            Id = 117,
                            Priority = 1,
                            ProductVarietyId = 30,
                            Query = "cliffton avokado"
                        },
                        new
                        {
                            Id = 118,
                            Priority = 2,
                            ProductVarietyId = 30,
                            Query = "clifton avokado"
                        },
                        new
                        {
                            Id = 119,
                            Priority = 3,
                            ProductVarietyId = 30,
                            Query = "cliffton avocado"
                        },
                        new
                        {
                            Id = 121,
                            Priority = 1,
                            ProductVarietyId = 31,
                            Query = "bergamot"
                        },
                        new
                        {
                            Id = 122,
                            Priority = 2,
                            ProductVarietyId = 31,
                            Query = "bergamot kg"
                        },
                        new
                        {
                            Id = 123,
                            Priority = 3,
                            ProductVarietyId = 31,
                            Query = "bergamot fiyat"
                        },
                        new
                        {
                            Id = 125,
                            Priority = 1,
                            ProductVarietyId = 32,
                            Query = "kumkuat"
                        },
                        new
                        {
                            Id = 126,
                            Priority = 2,
                            ProductVarietyId = 32,
                            Query = "kamkat"
                        },
                        new
                        {
                            Id = 127,
                            Priority = 3,
                            ProductVarietyId = 32,
                            Query = "kumkuat kg"
                        },
                        new
                        {
                            Id = 129,
                            Priority = 1,
                            ProductVarietyId = 33,
                            Query = "sadok"
                        },
                        new
                        {
                            Id = 130,
                            Priority = 2,
                            ProductVarietyId = 33,
                            Query = "pomelo greyfurt"
                        },
                        new
                        {
                            Id = 131,
                            Priority = 3,
                            ProductVarietyId = 33,
                            Query = "sadok fiyat"
                        },
                        new
                        {
                            Id = 133,
                            Priority = 1,
                            ProductVarietyId = 34,
                            Query = "beyaz greyfurt"
                        },
                        new
                        {
                            Id = 134,
                            Priority = 2,
                            ProductVarietyId = 34,
                            Query = "white grapefruit"
                        },
                        new
                        {
                            Id = 135,
                            Priority = 3,
                            ProductVarietyId = 34,
                            Query = "beyaz greyfurt kg"
                        },
                        new
                        {
                            Id = 137,
                            Priority = 1,
                            ProductVarietyId = 35,
                            Query = "kirmizi greyfurt"
                        },
                        new
                        {
                            Id = 138,
                            Priority = 2,
                            ProductVarietyId = 35,
                            Query = "red grapefruit"
                        },
                        new
                        {
                            Id = 139,
                            Priority = 3,
                            ProductVarietyId = 35,
                            Query = "kirmizi greyfurt kg"
                        });
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.ProductVariety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HarvestPeriod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique();

                    b.ToTable("ProductVarieties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HarvestPeriod = "Eylul sonu",
                            IsActive = true,
                            Name = "OKITSU",
                            Notes = "Cekirdeksiz; ilk donem eksimsi, sonra tatlilasir; ilk hasatta yesil.",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            HarvestPeriod = "Ekim sonu - Kasim",
                            IsActive = true,
                            Name = "SATSUMA",
                            Notes = "Cekirdeksiz; sulu ve tatli.",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            HarvestPeriod = "Kasim sonu",
                            IsActive = true,
                            Name = "KLEMANTIN",
                            Notes = "Cekirdekli; yogun aromali; kisa hasat donemi.",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            HarvestPeriod = "Ocak sonu",
                            IsActive = true,
                            Name = "ORRI",
                            Notes = "Cok tatli; sulu ve aromatik; az cekirdek gorulebilir.",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            HarvestPeriod = "Ocak sonu",
                            IsActive = true,
                            Name = "MURCOTT",
                            Notes = "Cekirdekli; yogun tatli, hafif eksi; sert ve parlak kabuklu.",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 6,
                            HarvestPeriod = "Eylul basi",
                            IsActive = true,
                            Name = "MAYER",
                            Notes = "Mandalina-limon aromasi; az asitli, bol sulu.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "KIRMIZI LIMON",
                            Notes = "Portakal ve limon karisimi aroma; cekirdekli; hafif eksi.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            HarvestPeriod = "Eylul sonu",
                            IsActive = true,
                            Name = "ENTERDONAT",
                            Notes = "En eksi limon; kalin kabuklu.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 9,
                            HarvestPeriod = "Aralik - Nisan",
                            IsActive = true,
                            Name = "LAMAS",
                            Notes = "Klasik limon; tam limon aromasi; cay icin ideal.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 10,
                            HarvestPeriod = "Mart basi",
                            IsActive = true,
                            Name = "KOKULU LIMON",
                            Notes = "Limonata icin ideal; cok sulu.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "GRANDE",
                            Notes = "Italyan kokenli; kalin kabuklu; recel ve iceceklerde kullanilir.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "TATLI LIMON",
                            Notes = "Eksilik yoktur; limonata icin uygundur.",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "LIME",
                            Notes = "Ince kabuklu; sulu; aromasi yuksek.",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "KAFFIR LIME",
                            Notes = "Cok yogun aroma; az sulu; yemek ve soslarda kullanilir.",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "TATLI LIME",
                            Notes = "Mandalinaya benzer; eksi degil, tatlidir.",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "KAN LIME",
                            Notes = "Kirmizi tonlu; nadir cesit.",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "VERDE",
                            Notes = "Finger lime; keskin aroma; asidi yuksek; parlak yesil taneler.",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "ROSE",
                            Notes = "Finger lime; pembe taneli; asidi dengeli; daha sulu.",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "SUNPEARL",
                            Notes = "Finger lime; sari-yesil; mat ve sert taneli.",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "BLOSSOM",
                            Notes = "Finger lime; uzun ve iri taneli.",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 21,
                            HarvestPeriod = "Kasim basi",
                            IsActive = true,
                            Name = "WASHINGTON",
                            Notes = "Finike portakali; cok tatli; cekirdeksiz.",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 22,
                            HarvestPeriod = "Nisan - Eylul",
                            IsActive = true,
                            Name = "VALENSIYA",
                            Notes = "Cekirdekli; sikmalik ve yemelik.",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Name = "MYSTICRIMSON",
                            Notes = "Kirmizi etli; hafif eksimsi; ince kabuklu.",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Name = "BLUSHSWEET",
                            Notes = "Kan portakali; pembe ic renk; tatli; ince kabuklu.",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Name = "SEKER PORTAKALI",
                            Notes = "Cok tatli; asidi dusuk.",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            Name = "HASS",
                            Notes = "Puturlu avokado; en yuksek yag orani; guclu aroma.",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            Name = "ETTINGER",
                            Notes = "Armut sekilli; parlak kabuklu.",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            Name = "BACON",
                            Notes = "Ince kabuklu; hafif lezzetli.",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 29,
                            IsActive = true,
                            Name = "FUERTE",
                            Notes = "Hafif puturlu; ince kabuklu.",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 30,
                            IsActive = true,
                            Name = "CLIFFTON",
                            Notes = "Yag orani dusuk; sulu yapi.",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 31,
                            IsActive = true,
                            Name = "BERGAMOT",
                            Notes = "Meyvesi yenmez; kabugu recel ve cayda kullanilir.",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 32,
                            IsActive = true,
                            Name = "KUMKUAT",
                            Notes = "Kabuguyla yenir; disi tatli, ici eksi.",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 33,
                            IsActive = true,
                            Name = "SADOK",
                            Notes = "Pomelo + greyfurt aromasi; kalin kabuklu.",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 34,
                            IsActive = true,
                            Name = "BEYAZ GREYFURT",
                            Notes = "Beyaz ic ve dis renk.",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 35,
                            IsActive = true,
                            Name = "KIRMIZI GREYFURT",
                            Notes = "Kirmizi ic renk; daha yumusak tat.",
                            ProductId = 7
                        });
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.PriceRecord", b =>
                {
                    b.HasOne("BahceFiyatTakip.Models.Market", "Market")
                        .WithMany("PriceRecords")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BahceFiyatTakip.Models.Product", "Product")
                        .WithMany("PriceRecords")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BahceFiyatTakip.Models.ProductVariety", "ProductVariety")
                        .WithMany("PriceRecords")
                        .HasForeignKey("ProductVarietyId");

                    b.Navigation("Market");

                    b.Navigation("Product");

                    b.Navigation("ProductVariety");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.ProductSearchAlias", b =>
                {
                    b.HasOne("BahceFiyatTakip.Models.ProductVariety", "ProductVariety")
                        .WithMany("SearchAliases")
                        .HasForeignKey("ProductVarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariety");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.ProductVariety", b =>
                {
                    b.HasOne("BahceFiyatTakip.Models.Product", "Product")
                        .WithMany("Varieties")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.Market", b =>
                {
                    b.Navigation("PriceRecords");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.Product", b =>
                {
                    b.Navigation("PriceRecords");

                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("BahceFiyatTakip.Models.ProductVariety", b =>
                {
                    b.Navigation("PriceRecords");

                    b.Navigation("SearchAliases");
                });
#pragma warning restore 612, 618
        }
    }
}
